---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.1
_src_path: gh:quickplates/meta
description: Protocol Buffers API template 📜
projectname: protobuf
username: quickplates
