---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.2.1
_src_path: gh:quickplates/meta
description: Protocol Buffers API template 📜
project_name: protobuf
repository: https://github.com/quickplates/protobuf
username: quickplates
